const PIZZA_SIZE_INPUT = "PIZZA_SIZE_INPUT";
const PIZZA_TYPE_INPUT = "PIZZA_TYPE_INPUT";
const VOUCHER_ID_INPUT = "VOUCHER_ID_INPUT";
const NAME_INPUT = "NAME_INPUT";
const PHONE_INPUT = "PHONE_INPUT";
const EMAIL_INPUT = "EMAIL_INPUT";
const ADDRESS_INPUT = "ADDRESS_INPUT";
const MESSAGE_INPUT = "MESSAGE_INPUT";

export {
    PIZZA_SIZE_INPUT,
    PIZZA_TYPE_INPUT,
    VOUCHER_ID_INPUT,
    NAME_INPUT,
    PHONE_INPUT,
    EMAIL_INPUT,
    ADDRESS_INPUT,
    MESSAGE_INPUT
};