//Base URL
const BASE_URL_ORDERS = "http://203.171.20.210:8080/devcamp-pizza365/orders";
const BASE_URL_VOUCHERS = "http://203.171.20.210:8080/devcamp-pizza365/vouchers/";
const BASE_URL_DRINKS = "http://203.171.20.210:8080/devcamp-pizza365/drinks";

//Fetch Orders status
const FETCH_ORDERS_PENDING = "FETCH_ORDERS_PENDING";
const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
const FETCH_ORDERS_ERROR = "FETCH_ORDERS_ERROR"

//Pagination 
const PAGINATION_CHANGE = "PAGINATION_CHANGE";

//Drinks
//Call API, method GET
const FETCH_DRINKS_PENDING = "FETCH_DRINKS_PENDING";
const FETCH_DRINKS_SUCCESS = "FETCH_DRINKS_SUCCESS";
const FETCH_DRINKS_ERROR = "FETCH_DRINKS_ERROR"
//Select drink
const SELECT_DRINK = "SELECT_DRINK";


//Vouchers
//Call API, method GET
const FETCH_VOUCHERS_PENDING = "FETCH_VOUCHERS_PENDING";
const FETCH_VOUCHERS_SUCCESS = "FETCH_VOUCHERS_SUCCESS";
const FETCH_VOUCHERS_ERROR = "FETCH_VOUCHERS_ERROR"


export {
    BASE_URL_ORDERS,
    BASE_URL_VOUCHERS,
    BASE_URL_DRINKS,
    FETCH_ORDERS_PENDING,
    FETCH_ORDERS_SUCCESS,
    FETCH_ORDERS_ERROR,
    PAGINATION_CHANGE,
    FETCH_DRINKS_PENDING,
    FETCH_DRINKS_SUCCESS,
    FETCH_DRINKS_ERROR,
    SELECT_DRINK,
    FETCH_VOUCHERS_PENDING,
    FETCH_VOUCHERS_SUCCESS,
    FETCH_VOUCHERS_ERROR
};